-- Migration: initial_schema
-- Project: CAPPY
-- Generated by: Database Engineer Agent

BEGIN;

-- ── TABLES ──────────────────────────────────────────────────────────────────

-- Table: leads
-- Description: Stores waitlist signups for future drops
CREATE TABLE IF NOT EXISTS public.leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    full_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    email_address TEXT NOT NULL UNIQUE,
    status TEXT DEFAULT 'waitlist'
);

-- ── INDEXES ─────────────────────────────────────────────────────────────────

-- Index for unique email lookups and performance
CREATE INDEX IF NOT EXISTS idx_leads_email_address ON public.leads(email_address);

-- ── ROW LEVEL SECURITY ───────────────────────────────────────────────────────

ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anonymous service-side inserts (via Anon/Service Role)
-- Note: Using IF NOT EXISTS via a DO block since CREATE POLICY doesn't support it directly in all PG versions
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'leads' AND policyname = 'Enable insert for everyone'
    ) THEN
        CREATE POLICY "Enable insert for everyone" ON public.leads
            FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'leads' AND policyname = 'Admins can view leads'
    ) THEN
        CREATE POLICY "Admins can view leads" ON public.leads
            FOR SELECT USING (auth.role() = 'service_role');
    END IF;
END
$$;

COMMIT;